<?php

$labels = array();
$labels['vacation'] = 'Abwesenheit';
$labels['vacationenable'] = 'Aktiv';
$labels['vacationsubject'] = 'Betreff';
$labels['vacationmessage'] = 'Nachricht';
$labels['vacationforwarder'] = 'Weiterleitadresse';
$labels['vacationstart'] = 'Anfang';
$labels['vacationend'] = 'Ende';
$labels['period'] = 'Dauer';
$labels['frequency'] = 'Häufigkeit';
$labels['addressed_to'] = 'Adressiert an';
$labels['append_subject'] = 'Betreff hinzufügen';
$labels['send_from'] = 'Versenden von';
$labels['vacationfrom'] = 'von';
$labels['vacationto'] = 'bis';
$labels['answer_no_more_than_every'] = 'antworten nicht öffter als jeden';
$labels['vacationdays'] = 'Tag';
$labels['wholeday'] = 'ganzen Tag';

$messages = array();
$messages['vacationinvalidstartdate'] = 'Bitte wählen Sie ein gültiges Startdatum.';
$messages['vacationinvalidenddate'] = 'Bitte wählen Sie ein gültiges Enddatum.';
$messages['vacationinvaliddateinterval'] = 'Das Intervall der Date ist ungültig.';
$messages['vacationnosubject'] = 'Bitte geben Sie den Betreff Ihrer Abwesenheitsnachricht an.';
$messages['vacationnomessage'] = 'Bitte geben Sie den Text Ihrer Abwesenheitsnachricht an.';
$messages['vacationinvalidforwarder'] = 'Die Weiterleitadresse ist ungültig.';
$messages['vacationinvalidforwarders'] = 'Die Weiterleitadressen sind ungültig.';
$messages['vacationdriverdefaulterror'] = 'Unbekannter Ausführungsfehler';
$messages['vacationdriverconnecterror'] = 'Fehler bei der Verbindung';
$messages['vacationdriverprocesserror'] = 'Fehler bei der Verarbeitung';

