<?php

$labels = array();
$labels['vacation'] = 'Vacation';
$labels['vacationenable'] = 'Enable';
$labels['vacationsubject'] = 'Subject';
$labels['vacationmessage'] = 'Message';
$labels['vacationforwarder'] = 'Forward address';
$labels['vacationstart'] = 'Start';
$labels['vacationend'] = 'End';
$labels['period'] = 'Period';
$labels['frequency'] = 'Frequency';
$labels['addressed_to'] = 'Addressed to';
$labels['append_subject'] = 'Append subject';
$labels['send_from'] = 'Send from';
$labels['vacationfrom'] = 'From';
$labels['vacationto'] = 'To';
$labels['answer_no_more_than_every'] = 'Answer no more than every';
$labels['vacationdays'] = 'days';

$messages = array();
$messages['vacationinvalidstartdate'] = 'Please select a valid start date.';
$messages['vacationinvalidenddate'] = 'Please select a valid end date.';
$messages['vacationinvaliddateinterval'] = 'The date interval is not valid.';
$messages['vacationnosubject'] = 'Please fill the subject of your vacation.';
$messages['vacationnomessage'] = 'Please fill the message of your vacation.';
$messages['vacationinvalidforwarder'] = 'The forward address is not valid.';
$messages['vacationinvalidforwarders'] = 'The forward addresses list is not valid.';
$messages['vacationdriverdefaulterror'] = 'Unknown execution error';
$messages['vacationdriverconnecterror'] = 'Error during connection';
$messages['vacationdriverprocesserror'] = 'Error during processing';

?>
